use("escuela")
db.alumnos.findOne({Nombre: "Makii"})
db.alumnos.findOne({Nombre: "Richie"})
db.alumnos.findOne({Nombre: "Misael"})
db.alumnos.findOne({Nombre: "Angel"})
db.alumnos.findOne({Nombre: "Sarai"})
db.alumnos.findOne({Nombre: "Abraham"})
db.alumnos.findOne({Nombre: "Alondra"})
db.alumnos.findOne({Nombre: "Juan"})
db.alumnos.find({Edad: 17})
db.alumnos.find({Especialidad: "Programacion"})
db.profesores.findOne({Nombre: "Samuel"})
db.profesores.findOne({Nombre: "Hector"})
db.profesores.findOne({Nombre: "Minerva"})
db.profesores.findOne({Nombre: "Martha"})
db.profesores.findOne({Nombre: "Guadalupe"})
db.profesores.findOne({Nombre: "Carlos"})
db.profesores.findOne({Nombre: "Raul"})
db.profesores.findOne({Materia: "Español"})
db.profesores.findOne({Materia: "Matematicas"})
db.profesores.findOne({Materia: "Ingles"})
db.cursos.findOne({Nombre: "Lectura y Analisis"})
db.cursos.findOne({Nombre: "Reseña de Textos"})
db.cursos.findOne({Nombre: "Teaching Feeling"})
db.cursos.findOne({Nombre: "Units X-play"})
db.cursos.findOne({Nombre: "Formando el Futuro"})
db.cursos.findOne({Nombre: "Jovenes por México"})
db.cursos.findOne({Nombre: "Python"})
db.cursos.findOne({Nombre: "MongoDB"})
db.cursos.findOne({Materia: "Programacion"})
db.cursos.findOne({Materia: "Español"})
db.grupos.findOne({Grado: 1})
db.grupos.findOne({Grado: 2})
db.grupos.findOne({Grado: 3})
db.grupos.findOne({Grado: 4})
db.grupos.findOne({Grado: 5})
db.grupos.find({Grupo: {$eq: "A"}})
db.grupos.find({Grupo: {$eq: "B"}})
db.grupos.find({Grupo: {$eq: "C"}})
db.grupos.find({Grupo: "D"})
db.grupos.find({Grado: {$eq: 1}})
db.administrativos.findOne({Nombre: "Albert"})
db.administrativos.findOne({Nombre: "Pablo"})
db.administrativos.findOne({Nombre: "Miguel"})
db.administrativos.findOne({Nombre: "Angel"})
db.administrativos.findOne({Nombre: "Haziel"})
db.administrativos.findOne({Nombre: "David"})
db.administrativos.findOne({Nombre: "Emanuel"})
db.administrativos.findOne({Nombre: "Ruslan"})
db.administrativos.findOne({Cargo: "Director"})
db.administrativos.find({Cargo: {$eq: "Secretario"}})